// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using challenge.Database;

namespace challenge.Migrations
{
    [DbContext(typeof(ChallengeDbContext))]
    [Migration("20220801183823_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("challenge.Database.NoteDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = "13ce93ef-00f0-4fd9-bad0-b4dd9b6bd64a",
                            Content = "1 Bund Möhren\r\n5 Äpfel\r\n2 Bananen\r\nKiste Bier",
                            Title = "Einkaufszettel"
                        },
                        new
                        {
                            Id = "ab858028-3d7f-448c-b890-e57bca294fc6",
                            Content = "wird 70, anrufen!!!!!!!!!",
                            Title = "Schwiegermutter"
                        },
                        new
                        {
                            Id = "4958d9b7-44e5-409a-8062-497769b5fcb2",
                            Content = "Miete am 1. überweisen",
                            Title = "Bank"
                        },
                        new
                        {
                            Id = "2a1f9ad0-808a-4881-b03d-24c57ecdce5d",
                            Content = "Challenge umsetzen",
                            Title = "Arbeit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
